name: Update Org README

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SD_BOT_PAT }}
        with:
          source_file: 'README.md'
          destination_repo: 'spacedriveapp/.github'
          destination_folder: 'profile'
          user_email: 'actions@spacedrive.com'
          user_name: 'GH Actions'
          commit_message: 'Update README'
